# Generated by Django 4.1.1 on 2022-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplier_wcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='wcontract',
            name='quantily',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wcontract',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('DELIVERED', 'DELIVERED'), ('SETTLEMENTED', 'SETTLEMENTED')], default='PENDING', max_length=100),
        ),
    ]
