# Generated by Django 4.1.1 on 2022-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wcontract_quantily_wcontract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(to='core.component'),
        ),
    ]
