# Generated by Django 4.1.1 on 2022-10-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_machine_order_subtask_task_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('DELIVERED', 'DELIVERED'), ('SETTLEMENTED', 'SETTLEMENTED')], default='PENDING', max_length=100)),
                ('quantily', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='SaleOrder',
        ),
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='SaleOrderDetail',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Component', 'verbose_name_plural': '1. Components'},
        ),
        migrations.DeleteModel(
            name='PurchaseContract',
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
    ]
