# Generated by Django 4.1.1 on 2022-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchaseorder_purchaseorderdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': '2.1 Customers'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': '2.2 Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': '2. Products'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'PurchaseOrder', 'verbose_name_plural': '1.3 PurchaseOrder'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={'verbose_name': 'PurchaseOrderDetail', 'verbose_name_plural': '1.3.1 PurchaseOrderDetail'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'verbose_name': 'SaleOrder', 'verbose_name_plural': '2.3 SaleOrder'},
        ),
        migrations.AlterModelOptions(
            name='saleorderdetail',
            options={'verbose_name': 'SaleOrderDetail', 'verbose_name_plural': '2.3.1 SaleOrderDetail'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': '1.2 Stock'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': '1.1 Suppliers'},
        ),
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(related_name='Assembly', to='core.component'),
        ),
    ]
